name: 2 Dockerfile MultiStage Build


#직접 수동 실행
on:
  workflow_dispatch:

#  push:
#    branches: ["main"]
#  pull_request:
#    branches: ["main"]


jobs:
  build-and-test:
    runs-on: ubuntu-latest


    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    
    - name: directory path check
      run: |
        pwd
        ls -al


#Set up JDK 11 단계를 지우면, Build with Maven 단계에서 mvn이나 java를 찾을 수 없는 에러가 발생할 수 있음
#   - name: Set up JDK 11
#    uses: actions/setup-java@v5
#    with:
#      java-version: '11'
#      distribution: 'temurin'
#cache: 'maven' # Maven 의존성 캐싱으로 빌드 속도 향상?

   # 3. Maven 빌드 및 jar 파일 생성
#   - name: Build with Maven
#     run: mvn clean package


    - name: dockerfile bilud
      run: docker build --tag todoproject:latest .



















        ### 도커파일 최적화 진행 필요



        ###ci.yml파일 작성 중, 생긴 의문들###

#1. 프로젝트 빌드를 어디서 할 것인가?
#==> 도커파일에 멀티스테이지빌드로? 혹은 깃허브 호스트 러너에서 빌드를 할 것인가?

#2. 도커파일을 빌드하고 run을 할텐데 그럼 DB서버는 어떻게 처리하나? 
#==> 도커컴파일로 띄우나? 아니면 flyway로? 아니면 또 다른 방법으로 ? 
#그리고 초기화 스크립트는 어떻게 처리 ? 


#3. 깃헙 호스트 러너에서 docker run을 해서 직접 확인하나? 
#==> docker run -d -p 8080:8080 app 이렇게 하고 curl localhost:8080/actuator/health로 직접 확인??

#참고# 
#runs-on: ubuntu-latest에 이미 도커가 설치되어 있음! 
        
