name: 04 Docker Multi Build and use buildkit-cache-dance


on:
#  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]


jobs:
  build-and-test:
    runs-on: ubuntu-latest


    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4


    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4
      with:
        version: latest
      id: setup-buildxxx


    - name: dependencies build cache
      uses: actions/cache@v4
      id: cache
      with:
        path: m2-build-cache
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2-
#        path: /tmp/m2-repository


#    - name: check dependencies
#      run: |
#        /tmp/m2-repository

#    - name: inject go-build-cache into docker
#      uses: reproducible-containers/buildkit-cache-dance@4b2444fec0c0fb9dbf175a96c094720a692ef810 # v2.1.4
#      with:
#        cache-source: m2-build-cache


#    - name: Restore Docker cache mounts
#      uses: reproducible-containers/buildkit-cache-dance@v3
#      with:
#        cache-map: |
#          {
#            "m2-build-cache" : "/root/.m2"
#          }

#        builder: ${{ steps.setup-buildxxx.outputs.name }}
#        skip-extraction: ${{ steps.cache.outputs.cache-hit }}



#    - name: Restore Docker cache mounts
#      uses: reproducible-containers/buildkit-cache-dance@v3
#      with:
#        builder: ${{ steps.setup-buildx.outputs.name }}
#        cache-dir: /tmp/m2-repository
#        dockerfile: dockerfile
#        skip-extraction: ${{ steps.cache.outputs.cache-hit }}


#    - name: Restore Docker cache mounts
#      uses: reproducible-containers/buildkit-cache-dance@v2.1.2
#      with:
#        cache-source: /tmp/m2-repository
#        cache-target: /root/.m2/repository


    - name: Build Dcoker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./dockerfile
        push: false
        tags: todoproject:latest
        cache-from: type=gha
        cache-to: type=gha, mode=max


#    - name: checke dependencies
#      run: |
#        ls -al
#        ls -al m2-repository

           
           
