name: 3-(2) Maven Build and Docker Build With Cache - Version1


on:
  workflow_dispatch:

        #  push:
        #    branches: ["main"]
        #  pull_request:
        #    branches: ["main"]


jobs:
  build-and-test:
    runs-on: ubuntu-latest


    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4


    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3




    - name: Cache
      uses: actions/cache@v4
      id: cache
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
#        뭔가 restore도 있어야 될 것 같은 느낌적인 느낌

        
    - name: Restore Docker cache mounts
      uses: reproducible-containers/buildkit-cache-dance@v3
      with:
        cache-source: ~/.m2/repository

#    - name: Build with Maven
#      run: mvn clean package

    - name: Build with Maven
      run: mvn -B dependency:go-offline




    - name: Build Dcoker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./dockerfile
        push: false
        tags: todoproject:latest
        cache-from: type=gha
        cache-to: type=gha, mode=max


