name: 04 Docker Multi Build and use buildkit-cache-dance


on:
#  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]


jobs:
  build-and-test:
    runs-on: ubuntu-latest


    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4


    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      id: setup-buildxxx


    - name: dependencies build cache
      uses: actions/cache@v4
      id: cache
      with:
        path: m2-repository
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
#       restore-keys가 없어도 됨. 다만 없으면 정확히 일치할 때문 캐시를 복원함
        restore-keys: ${{ runner.os }}-m2-

 

#     this is version2 style i guess 
#    - name: Restore Docker cache mounts
#      uses: reproducible-containers/buildkit-cache-dance@v2
#      with:
#        cache-source: ~/.m2/repository


    - name: Restore Docker cache mounts
      uses: reproducible-containers/buildkit-cache-dance@v3
      with:
        builder: ${{ steps.setup-buildxxx.outputs.name }}
        cache-dir: m2-repository
        dockerfile: ./dockerfile
        skip-extraction: ${{ steps.cache.outputs.cache-hit }}


         #     - name: Restore Docker cache mounts
         #       uses: reproducible-containers/buildkit-cache-dance@v3
         #       with:
         #         builder: ${{ steps.setup-buildx.outputs.name }}
         #         cache-dir: cache-mount
         #         cache-map: |
         #           {
         #                   ".": "/root/.m2/repository"
         #           }
         #         skip-extraction: ${{ steps.cache.outputs.cache-hit }}




#   이게 굳이 필요 없는 듯. 처음에 필요한 줄 알았으나
#    - name: Build with Maven
#      run: mvn -B dependency:go-offline


    - name: Build Dcoker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./dockerfile
        push: false
        tags: todoproject:latest
        cache-from: type=gha
        cache-to: type=gha, mode=max


    - name: checke dependencies
      run: |
           cd m2-repository 
           ls -al
      #      run: cd ~/.m2/repository |
      #           ls -al


